### ISSUE TITLE
pcb

### ISSUE THREAD

**Issue by svobik81** [icelord75/openHCOP#3]
On the printed circuit you have a reset pin on the wrong attiny pin

**Comment by icelord75** [comment]
you correct, added to "FIX IT"

**Comment by svobik81** [comment]
And I wonder why it can not be programmed for two days by either of the three programmers :-) :-) :-)
And then, from the emergency, it occurred to me to check it according to the datasheet  
I thank for a quick reaction 👍

**Comment by saldaogoiano** [comment]
How do I change the dwell time in your code? thanks

**Comment by icelord75** [comment]
> How do I change the dwell time in your code? thanks

Dwell time is controlled by ECU - module just translate it to COP mudule

You can prolong dwell time due update "ignition off" part of code with extra cycle delays
